### ISSUE TITLE
Is 'Learning Temporal Point Processes via Reinforcement Learning' only predict time of the next event,not type?

### ISSUE THREAD

**Issue by wencyxu** [meowoodie/Imitation-Learning-for-Point-Process#2]
Hello, I wanna ask if this paper is about using inverse RL to study the occurrence time of the next event in the point process, but does not involve predicting the type of the next event , right?

**Comment by meowoodie** [comment]
Yes, the proposed method in this 2018 paper only focuses on predicting event time.

**Comment by wencyxu** [comment]
I got it.Thanks!
